export const colors = {
  WHITE: '#fff',
  QUEEN_BLUE: '#3a6ea5',
  BLACK: '#000',
  ATENEO_BLUE: '#08466c',
  CYAN_CORNFLOWER_BLUE: '#2883b5',
};
export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_SIZE_XLARGE: 20,

  PRIMARY_COLOR: 'rgb(30, 147, 242)',
  SECONDARY_COLOR: 'rgb(238, 167, 2)',
  FONT_WEIGHT_LIGHT: 200,
  FONT_WEIGHT_MEDIUM: '600',
  FONT_WEIGHT_HEAVY: 800,
  FONT_WEIGHT_BOLD: 'bold',
  APP_THEME_COLOR: colors.QUEEN_BLUE,
  APP_TEXT_THEME_COLOR: colors.CYAN_CORNFLOWER_BLUE,
};
